/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiV1GenerateRouteImport } from './routes/api/v1/generate'
import { Route as ApiPublicIndexnowRouteImport } from './routes/api/public/indexnow'
import { Route as ApiPublicAfdianRouteImport } from './routes/api/public/afdian'
import { Route as ApiEmailSuppressionRouteImport } from './routes/api/email/suppression'
import { Route as ApiAiStreamRouteImport } from './routes/api.ai.stream'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin.admin.projects'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin.admin.orders'
import { Route as AdminAdminCreditsRouteImport } from './routes/_admin.admin.credits'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin.admin.coupons'
import { Route as ApiEmailTransactionalSendRouteImport } from './routes/api/email/transactional/send'
import { Route as ApiEmailTransactionalPreviewRouteImport } from './routes/api/email/transactional/preview'
import { Route as ApiEmailQueueProcessRouteImport } from './routes/api/email/queue/process'
import { Route as ApiEmailAuthWebhookRouteImport } from './routes/api/email/auth/webhook'
import { Route as ApiEmailAuthPreviewRouteImport } from './routes/api/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1GenerateRoute = ApiV1GenerateRouteImport.update({
  id: '/api/v1/generate',
  path: '/api/v1/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIndexnowRoute = ApiPublicIndexnowRouteImport.update({
  id: '/api/public/indexnow',
  path: '/api/public/indexnow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAfdianRoute = ApiPublicAfdianRouteImport.update({
  id: '/api/public/afdian',
  path: '/api/public/afdian',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSuppressionRoute = ApiEmailSuppressionRouteImport.update({
  id: '/api/email/suppression',
  path: '/api/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStreamRoute = ApiAiStreamRouteImport.update({
  id: '/api/ai/stream',
  path: '/api/ai/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCreditsRoute = AdminAdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEmailTransactionalSendRoute =
  ApiEmailTransactionalSendRouteImport.update({
    id: '/api/email/transactional/send',
    path: '/api/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailTransactionalPreviewRoute =
  ApiEmailTransactionalPreviewRouteImport.update({
    id: '/api/email/transactional/preview',
    path: '/api/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailQueueProcessRoute = ApiEmailQueueProcessRouteImport.update({
  id: '/api/email/queue/process',
  path: '/api/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthWebhookRoute = ApiEmailAuthWebhookRouteImport.update({
  id: '/api/email/auth/webhook',
  path: '/api/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthPreviewRoute = ApiEmailAuthPreviewRouteImport.update({
  id: '/api/email/auth/preview',
  path: '/api/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/s/$slug': typeof SSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/afdian': typeof ApiPublicAfdianRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/api/v1/generate': typeof ApiV1GenerateRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/s/$slug': typeof SSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/afdian': typeof ApiPublicAfdianRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/api/v1/generate': typeof ApiV1GenerateRoute
  '/admin': typeof AdminAdminIndexRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/s/$slug': typeof SSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/_admin/admin/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin/credits': typeof AdminAdminCreditsRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/email/suppression': typeof ApiEmailSuppressionRoute
  '/api/public/afdian': typeof ApiPublicAfdianRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/api/v1/generate': typeof ApiV1GenerateRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/transactional/preview': typeof ApiEmailTransactionalPreviewRoute
  '/api/email/transactional/send': typeof ApiEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/unsubscribe'
    | '/docs/$slug'
    | '/email/unsubscribe'
    | '/p/$projectId'
    | '/project/$projectId'
    | '/s/$slug'
    | '/share/$token'
    | '/admin/coupons'
    | '/admin/credits'
    | '/admin/orders'
    | '/admin/projects'
    | '/admin/users'
    | '/api/ai/stream'
    | '/api/email/suppression'
    | '/api/public/afdian'
    | '/api/public/indexnow'
    | '/api/v1/generate'
    | '/admin/'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/unsubscribe'
    | '/docs/$slug'
    | '/email/unsubscribe'
    | '/p/$projectId'
    | '/project/$projectId'
    | '/s/$slug'
    | '/share/$token'
    | '/admin/coupons'
    | '/admin/credits'
    | '/admin/orders'
    | '/admin/projects'
    | '/admin/users'
    | '/api/ai/stream'
    | '/api/email/suppression'
    | '/api/public/afdian'
    | '/api/public/indexnow'
    | '/api/v1/generate'
    | '/admin'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/unsubscribe'
    | '/docs/$slug'
    | '/email/unsubscribe'
    | '/p/$projectId'
    | '/project/$projectId'
    | '/s/$slug'
    | '/share/$token'
    | '/_admin/admin/coupons'
    | '/_admin/admin/credits'
    | '/_admin/admin/orders'
    | '/_admin/admin/projects'
    | '/_admin/admin/users'
    | '/api/ai/stream'
    | '/api/email/suppression'
    | '/api/public/afdian'
    | '/api/public/indexnow'
    | '/api/v1/generate'
    | '/_admin/admin/'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/api/email/transactional/preview'
    | '/api/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PProjectIdRoute: typeof PProjectIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SSlugRoute: typeof SSlugRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAiStreamRoute: typeof ApiAiStreamRoute
  ApiEmailSuppressionRoute: typeof ApiEmailSuppressionRoute
  ApiPublicAfdianRoute: typeof ApiPublicAfdianRoute
  ApiPublicIndexnowRoute: typeof ApiPublicIndexnowRoute
  ApiV1GenerateRoute: typeof ApiV1GenerateRoute
  ApiEmailAuthPreviewRoute: typeof ApiEmailAuthPreviewRoute
  ApiEmailAuthWebhookRoute: typeof ApiEmailAuthWebhookRoute
  ApiEmailQueueProcessRoute: typeof ApiEmailQueueProcessRoute
  ApiEmailTransactionalPreviewRoute: typeof ApiEmailTransactionalPreviewRoute
  ApiEmailTransactionalSendRoute: typeof ApiEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/generate': {
      id: '/api/v1/generate'
      path: '/api/v1/generate'
      fullPath: '/api/v1/generate'
      preLoaderRoute: typeof ApiV1GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/indexnow': {
      id: '/api/public/indexnow'
      path: '/api/public/indexnow'
      fullPath: '/api/public/indexnow'
      preLoaderRoute: typeof ApiPublicIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/afdian': {
      id: '/api/public/afdian'
      path: '/api/public/afdian'
      fullPath: '/api/public/afdian'
      preLoaderRoute: typeof ApiPublicAfdianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/suppression': {
      id: '/api/email/suppression'
      path: '/api/email/suppression'
      fullPath: '/api/email/suppression'
      preLoaderRoute: typeof ApiEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/stream': {
      id: '/api/ai/stream'
      path: '/api/ai/stream'
      fullPath: '/api/ai/stream'
      preLoaderRoute: typeof ApiAiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/credits': {
      id: '/_admin/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminAdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/coupons': {
      id: '/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/email/transactional/send': {
      id: '/api/email/transactional/send'
      path: '/api/email/transactional/send'
      fullPath: '/api/email/transactional/send'
      preLoaderRoute: typeof ApiEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/transactional/preview': {
      id: '/api/email/transactional/preview'
      path: '/api/email/transactional/preview'
      fullPath: '/api/email/transactional/preview'
      preLoaderRoute: typeof ApiEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/queue/process': {
      id: '/api/email/queue/process'
      path: '/api/email/queue/process'
      fullPath: '/api/email/queue/process'
      preLoaderRoute: typeof ApiEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/webhook': {
      id: '/api/email/auth/webhook'
      path: '/api/email/auth/webhook'
      fullPath: '/api/email/auth/webhook'
      preLoaderRoute: typeof ApiEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/preview': {
      id: '/api/email/auth/preview'
      path: '/api/email/auth/preview'
      fullPath: '/api/email/auth/preview'
      preLoaderRoute: typeof ApiEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminCreditsRoute: typeof AdminAdminCreditsRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminCreditsRoute: AdminAdminCreditsRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PProjectIdRoute: PProjectIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SSlugRoute: SSlugRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAiStreamRoute: ApiAiStreamRoute,
  ApiEmailSuppressionRoute: ApiEmailSuppressionRoute,
  ApiPublicAfdianRoute: ApiPublicAfdianRoute,
  ApiPublicIndexnowRoute: ApiPublicIndexnowRoute,
  ApiV1GenerateRoute: ApiV1GenerateRoute,
  ApiEmailAuthPreviewRoute: ApiEmailAuthPreviewRoute,
  ApiEmailAuthWebhookRoute: ApiEmailAuthWebhookRoute,
  ApiEmailQueueProcessRoute: ApiEmailQueueProcessRoute,
  ApiEmailTransactionalPreviewRoute: ApiEmailTransactionalPreviewRoute,
  ApiEmailTransactionalSendRoute: ApiEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
